### ISSUE TITLE
Error: Module "arch" not found

### ISSUE THREAD

**Issue by umoqnier** [archlinuxmx/archlinuxmx.github.io#9]
Intenté instalar usando las instrucciones pero parece que faltan detalles del tema o no sé si mi versión de `hugo` no es compatible.

- **Hugo version**: `v0.65.0-DEV/extended linux/amd64 BuildDate: unknown`
- **¿Cómo replicar el error?**: Ejecutando comando `$ hugo server -D`
- **screenshot**:

![image](https://user-images.githubusercontent.com/13933292/98317535-48b64580-1fa2-11eb-8c22-09e54ed74911.png)

**Comment by jcstr** [comment]
Hola @umoqnier! Muchas gracias por ayudar en este proyecto!

No hay ningún problema con la versión de `hugo` que estás usando, en realidad sólo hace falta el tema que estamos usando, el cual es: [hugo-theme-arch](https://github.com/syui/hugo-theme-arch)

Te marca error por que está indicado en el archivo `config.toml` pero no está en la carpeta themes.

Yo con gusto me encargo de agregar el tema directamente a este repo para que todos lo tengamos listo y funcionando.
¿Qué opinan? @da-edra @SantiagoTorres

**Comment by denisse-dev** [comment]
@jcstr podrías de favor agregar eso paso a la documentación?

El tema no debe estar en este repositorio ya que es una dependencia externa y tendríamos que estar pendientes de si se actualiza en su repositorio original para actualizarlo en nuestro repositorio. Las dependencias solo deben ser importadas pero no deben estar en el código de este proyecto.

Lo que necesitamos un Makefile que descargue el tema y haga el build del sitio, también agregar al `.gitignore` el directorio donde se descargaría el tema para no tenerlo en control de versiones.

**Comment by jcstr** [comment]
Va, yo me encargo de actualizar la documentación.

**Comment by denisse-dev** [comment]
Okay, yo trabajaré en el Makefile.

**Comment by denisse-dev** [comment]
Cerrado en #10 .
